### ISSUE TITLE
打字搜尋出現 500 error

### ISSUE THREAD

**Issue by geniusgordon** [henryyang42/NTHU_Course#99]
![image](https://cloud.githubusercontent.com/assets/8642924/15745540/eef1db3c-2897-11e6-9a31-3968fb4f7a7f.png)

![image](https://cloud.githubusercontent.com/assets/8642924/15745532/e5da1208-2897-11e6-9e62-3e6eea5b70aa.png)

**Comment by afq984** [comment]
人品問題

**Comment by yutzuhsuan** [comment]
大四要修普物？

**Comment by henryyang42** [comment]
We are sorry to inform you that `人品問題` is unsolvable. I cannot reproduce the issue on my environment.

**Comment by hydai** [comment]
I can reproduce this issue on my firefox 46.0.1.
But it looks good on my chrome (´･_･`)

**Comment by leVirve** [comment]
I can reproduce the situation on both my Firefox and Chrome.

![default](https://cloud.githubusercontent.com/assets/7029882/15746435/1846709e-2909-11e6-9639-fbd86da11408.PNG)

**Comment by WenYuChen** [comment]
I clone the project of the latest version and rebuild it.
Finally, I found it work correctly.
May the 500-ERROR problem happened because of the running server?
(Although hydai said that server has been restarted)

![image](https://cloud.githubusercontent.com/assets/4236030/15755280/99e3872a-292e-11e6-9b59-887d302d4cf1.png)

**Comment by hydai** [comment]
After I deployed our project in new server, this problem is fixed.
